service: print-stocks-serverless

frameworkVersion: "2"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: "20201221"
  environment:
    STOCKS: ${env:STOCKS}

functions:
  printStocks:
    handler: dist/handlers/printStocks.handler
    memorySize: 2048
    timeout: 15
    layers:
      - arn:aws:lambda:${aws:region}:764866452798:layer:chrome-aws-lambda:31
